### PR TITLE
Adding DataTarget to HTML-Attributes

### PR DESCRIPTION
**Pull request by forki**
This attribute is needed for server-side rendering to render a menu button on mobile phones. Would appreciate a dot release. Thanks

/cc @horstoeko

### CODE REVIEW

**Comment by forki** [comment]
didn't know we can use the Data attribute

**Comment by MangelMaxime** [comment]
@forki Is the `data-target` attribute in the html standard ? If yes, then we should add it to the binding.

If this is a custom `data-*`attribute then indeed we should use the `Data` attribute.

**Comment by forki** [comment]
dunno

**Comment by forki** [comment]
but it's used by bootstrap for mobile stuff

**Comment by MangelMaxime** [comment]
Yes but bootstrap is evil :trollface: 

I did some search and in fact, we should not have `DataToggle` either the binding.

The standard say that we can create custom attribute if we need under `data-*`. 
[Specification](https://dev.w3.org/html5/spec-LC/elements.html#embedding-custom-non-visible-data-with-the-data-attributes)

Using `Data` helper is the right solution here.

**Pull request closed without merging**
