### PR TITLE
Add nothing to react helpers

### PR DESCRIPTION
**Pull request by vbfox**
React use `null` to signal that nothing should be rendered, it could be done before with `ofOption None` but this add clearer alternative to generate this.

```fsharp
let render props =
	let details =
		match props.Details with
		| Some d -> strong [] [str (sprintf " (%s)")] d
		| None -> nothing
	span [] [ str props.Name; details ]
```

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Nice one, thank you!

**Comment by forki** [comment]
awesome this reduces couple of yields for me. How can we make it mor popular? @theimowski something for the template?

**Comment by theimowski** [comment]
Yeah, maybe - created an issue

**Comment by MangelMaxime** [comment]
Just for reference you can also use `Option.map` to not use `yield`.

```fs
let private showFirstConnectionUrl (url : string) =
    Message.message [ Message.Color IsInfo ]
        [ Message.header [ ]
            [ str "Ce compte n'a pas encore été activé." ]
          Message.body [ ]
            [ CopyButton.copyButtton [ CopyButton.Value url ] ] ]

let private viewUserInfo (info : LoadedModel) dispatch =
    div [ ]
        [ info.OriginalData.FirstConnectionUrl
          |> Option.map showFirstConnectionUrl
          |> ofOption
          // More code... 
        ]
```

**Comment by forki** [comment]
Yes, but really like the explicit nothing function.

Am Di., 6. Nov. 2018, 11:05 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by vbfox** [comment]
Yes using `Option.Map + ofOption` is the other choice but for complex case I find `nothing` to be clearer and producing less noise instead having to add `Some`/`None` + `ofOption`, when starting with options in the model then it depends

**Pull request merged**
