### PR TITLE
Some API improvements

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
Also related to #33 

@MangelMaxime please review, I've renamed Width in HTML and SVG props to avoid conflicts, but maybe this is more confusion for users, what do you think?

To my surprise, the problem with mixed properties in SVG elements has been fixed just by removing the `#` in `svgEl` signature. You shouldn't have to cast to `IProp` anymore :)

The last fix we could do is just replace all the `U2<float, string>` with just `obj`. We'll lose a bit of type safety but we don't need to use the `!^` operator constantly (which @forki and I guess others don't like that much :wink:) and ints would also be accepted.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I think using `obj` instead of `U2<float, string>` isn't so bad. I don't think type checking that important here as we already use `obj` for the inline style which is much more frequent that people using SVG.

One equivalent exemple [here](https://github.com/fable-compiler/fable-react/blob/1ec1ba14ef813f4d109c847bed539923bb58b7d8/Fable.Helpers.React.fs#L279)

I don't think prefixing width and height with `HTML` or `SVG` are really a good benefit. User will not find them easily and also this sounds equivalent to `HTMLAttr.Width` for me.

One solution could be to declare the CSS properties after the HTML and SVG properties. Like so when doing `Width` it's the CSS one being used by default. But this change need to be tested into several production/big apps like mine, @forki ones, etc. to see the real impact. Could be much worse than just adding `CSSProp.Width` depending on the names collision.

**Comment by inosik** [comment]
> just replace all the U2<float, string> with just obj.

I'm not sure if this is a good idea. Using `obj` "forces" me to compile and try the app, or to look up the documentation, to find out if I gave the API the kind of object it expects.

`U2<float, string>` isn't perfect, too, but it's better than nothing.

**Comment by MangelMaxime** [comment]
@inosik I understand but as one of the type is string you can more or less pass anything false value by default on it and so need the runtime to check it.

Extreme example:
`div [ Width "I am a super valid string" ] [ ]`

Also, my idea by making everything an `obj` is to have a consistent API between `HTMLAttr` and `CSSProps`

@inosik I have some ideas to avoid this kind of problem, but I need time to think about it and prototype a library.

@alfonsogarciacaro I didn't saw that you pushed more commits on this PR last time. I will review it and test it.

**Comment by MangelMaxime** [comment]
Sorry for the small commit, I needed it to make Github happy. Was complaning about conflicts..

@alfonsogarciacaro For me it's seems ok. I got some few compilation errors but the compiler was here to help me fixing them.

Would be nice if @forki could take a look when he have time. And perhaps we could release a version 1.2.0-alpha just to be sure as we are doing small breaking changes here.

**Pull request merged**
