### PR TITLE
WIP: Repo split

### PR DESCRIPTION
**Pull request by MangelMaxime**
Follow up on https://github.com/fable-compiler/fable-react/pull/169

The package split of `Fable.React` is ready, there is already a beta version of [Fable.React.Dom](https://github.com/fable-compiler/fable-react-dom) published.

I am waiting for a solution to [Fable.Elmish.React](https://github.com/elmish/react/issues/43) split before realising everything to stable.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
This doesn't look ready!? because I see a lot of `react-dom` specific stuff still in here like Fable.React.Standard.fs, Props, Extensions etc... Now if Fable.ReactNative depends on Fable.React, they will have access to `div` and `h1` but they can't use them because they are `react-dom` specific..

**Comment by MangelMaxime** [comment]
Ah yes, indeed.

I thought that react-native was accepting the same components as the one from the browser my bad.

I will update the PR.

**Comment by Zaid-Ajaj** [comment]
I gave this split a try locally but it was soo messy because of the SSR stuff everywhere using compiler directives to generate html elements on the server, but now these stuff have to go to `fable-react-dom` or their own library?!

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime IIRC we never did the react/react-dom split at the end. Should we try to do it now that we are also splitting the types and the helpers?

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Because we are already doing a breaking changes with Fable.React.Types, indeed I think it would be a good opportunity to split the packages.

**Comment by alfonsogarciacaro** [comment]
What was the main motivation to remove react-dom btw? For cleanness or to avoid Femto using warnings in projects that don't need react-dom (like react native projects)?

**Comment by MangelMaxime** [comment]
I think it was to have a clean binding in term of dependencies.

For example, native project doesn't need react-dom and it would probably also make it cleaner which package is responsible for what. As before everything was mixed together between F# specific code, bindings for the React.Dom or for React itself

**Comment by alfonsogarciacaro** [comment]
Superseded by #234

**Pull request closed without merging**
